# Generated by Django 4.2.23 on 2025-09-02 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care_app', '0006_alter_emergencycontact_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('CAREGIVER', 'Caregiver')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='care_app.elderprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elder_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('elder', 'user', 'role')},
            },
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, related_name='assigned_elders', through='care_app.ElderAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
